language: objective-c
osx_image: xcode8

before_deploy: zip -r InMoment.framework.zip InMoment.framework

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file: InMoment.framework.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: pod trunk push
    on:
      tags: true
